[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  # This is necessary for Staticman to redirect back to this website.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[build.environment]
    NODE_VERSION = "18.12.0"
    NPM_VERSION = "8.19.2" 