backend:
  name: github
  repo: naezeroth/website

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  # - name: photos
  #   label: Photos
  #   folder: content/photos
  # - name: "projects" # Used in routes, e.g., /admin/collections/blog
  #   label: "Projects" # Used in the UI
  #   folder: "projects" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Customer", name: "customer", widget: "string"}
  #     - {label: "Activity", name: "activity", widget: "string"}
  #     - {label: "Date", name: "date", widget: "datetime"}
  #     - {label: "Link", name: "link", widget: "string"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Body", name: "body", widget: "markdown"}
